import { createSlice } from '@reduxjs/toolkit';
import { Notifications } from 'react-native-notifications';

const getCurrentTime = () => {
  var date = new Date();
  var dateStr =
    ("00" + date.getHours()).slice(-2) + ":" +
    ("00" + date.getMinutes()).slice(-2) + ":" +
    ("00" + date.getSeconds()).slice(-2);
  return dateStr;
}

export const bluetoothSlice = createSlice({
  name: 'bluetooth',
  initialState: {
    impulse: [0],
    maxForce: [0],
    angle: [0],
    battery: 0,
    impulseAxis: [getCurrentTime()],
    maxForceAxis: [getCurrentTime()],
  },
  reducers: {
    addImpulse: (state, action) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      //const temp = state.impulse;
      // For impulse, we want to accumulate all the impulses.
      const accumulateImpulse = state.impulse[state.impulse.length - 1] + action.payload.payload;
      state.impulse = [...state.impulse, accumulateImpulse];
      state.impulseAxis = [...state.impulseAxis, getCurrentTime()].slice(-6);
      // var sumImpulse = state.impulse[state.impulse.length - 1] + action.payload.payload;
      // temp.push(sumImpulse);
      // state.impulse = temp;
      // if (accumulateImpulse > 1000) {
      //   Notifications.postLocalNotification({
      //     title: "Local notification",
      //     body: "This notification was generated by the app!",
      //     extra: "data"
      // });
      //}
    },
    addMaxForce: (state, action) => {
      state.maxForce = [...state.maxForce, action.payload.payload];
      state.maxForceAxis = [...state.maxForceAxis, getCurrentTime()].slice(-6);
    },
    addAngle: (state, action) => {
      const temp = state.angle;
      temp.push(action.payload.payload);
      state.angle = temp;
    },
    clearImpulse: state => {
      state.impulse = [];
    },
    clearMaxForce: state => {
      state.maxForce = [];
    },
    clearAngle: state => {
      state.angle = [];
    },
    setImpulse: (state, action) => {
      state.impulse = action.payload;
    },
    setMaxForce: (state, action) => {
      state.maxForce = action.payload;
    },
    setBattery: (state, action) => {
      state.battery = action.payload;
    },
    setImpulseAxis: state => {
      state.impulseAxis = [...state.impulseAxis, getCurrentTime()].slice(-6);
    },
    setMaxForceAxis: state => {
      state.maxForceAxis = [...state.maxForceAxis, getCurrentTime()].slice(-6);
    }
  },
});

// Action creators are generated for each case reducer function
export const { addImpulse, addMaxForce, addAngle, clearImpulse, clearMaxForce,
  clearAngle, setImpulse, setMaxForce, setBattery, setImpulseAxis, setMaxForceAxis } = bluetoothSlice.actions;

export default bluetoothSlice.reducer;
